### PR TITLE
client.get_steps

### PR DESCRIPTION
**Pull request by ravescovi**

### CODE REVIEW

**Comment by NickolausDS** [comment]
What is this used for?

**Comment by ravescovi** [comment]
Once you get the steps in order. It is easy to make a function that
checks/waits for a particular step (XPCS+DM) or make a table of running
flows.
I don't mind dumping the flow_definition and invoking the get_ordered_steps
outside but it seems wasteful to not use the client.self since it is all
already defined.

**Comment by ravescovi** [comment]
It will also help raising the last known step or last step error/result.

**Comment by ravescovi** [comment]
Can we merge this?

**Comment by NickolausDS** [comment]
I see how this is useful for XPCS in a very narrow case, but not as a general feature for Gladier. Will other Gladier clients ever use this?

**Comment by ravescovi** [comment]
I will say yes. I have a very clear case that I need this.
given a set of flow_ids/run_ids I want to create a table of "info"/step

We can start phasing things out when they move to automate main

**Comment by NickolausDS** [comment]
I see your need to add this to the XPCS client, so why not start with it there and we can decide to add this as a general feature if it's needed elsewhere?

**Comment by ravescovi** [comment]
I was planning on using it on SSX too.
I guess my thinking of putting it here is that it would be defined into
every new instance of GladierClientBase we want to have the functionality.

What is the downside of merging it here?

**Comment by NickolausDS** [comment]
The downside is long term maintenance. We shouldn't try to implement every possible feature in this package, only the most common. That way we're not stuck with a bunch of legacy code that only some people use.

**Pull request merged**
