### PR TITLE
Upgrade globus-automate-client/funcx to globus-sdk v3 versions

### PR DESCRIPTION
**Pull request by NickolausDS**
Both the Globus Automate Client and FuncX have started migrations
to Globus SDK v3, but haven't published full releases yet. FuncX
also isn't yet functional, so this can't be merged until that point.

So far, there aren't any backwards incompatible changes which break
the tests, but that may change. Gladier WILL however need to drop
support for older versions of Globus Automate Client and FuncX due
to older versions requiring the older Globus SDK v2 dependency.

### CODE REVIEW

**Comment by ravescovi** [comment]
What does the change in funcx mean?

**Comment by NickolausDS** [comment]
> What does the change in funcx mean?

FuncX has a PR for using the Globus SDK v3, but it's still a WIP can't yet be used to register functions. I installed using this version, and tests pass ok, but we can't be certain it won't require some changes to Gladier until the PR is merged and they make a pre-release for us to test.

**Comment by NickolausDS** [comment]
I ran tar_and_transfer on the newest funcx update and smoketested some various activities (made it re-register the function, update the flow, deploy a new flow). Globus Automate Client seems fine too. So far all is looking good. No changes needed to Gladier.

**Comment by ravescovi** [comment]
Can we go forward with this one?

**Comment by NickolausDS** [comment]
No, we're blocked on a funcx release.

**Comment by NickolausDS** [comment]
The release is out! https://pypi.org/project/globus-automate-client/#history
I'll update with the latest version numbers and we can merge this. I'll make this a breaking change and drop support for Globus SDK v2 clients, so we're not stuck supporting both.

**Comment by ravescovi** [comment]
Perfect.

**Pull request merged**
