### PR TITLE
Funcx upgrade

### PR DESCRIPTION
**Pull request by NickolausDS**
Funcx 0.0.5 also depended on funcx-endpoint 0.0.3. funcx-endpoint
can be dropped in the next release, since adding it to gladier was
a convenience to ensure users didn't use the incompatible 0.2.3
package instead.

BREAKING CHANGE -- This will break all current funcx functions without
modification. Everyone will need to upgrade to the new funcX endpoint
package wherever they are executing functions. If manually generating
flow definitions, the following changes need to be made:

    'ActionUrl': 'https://automate.funcx.org',
    'ActionScope': 'https://auth.globus.org/scopes/b3db7e59-a6f1-4947-95c2-59d6b7a70f8c/action_all'

Additionally for funcx payloads the following

    'func.$': '$.input.'

Needs to be changed to:

    'function.$': '$.input.'

### CODE REVIEW

**Comment by ravescovi** [comment]
We may want to make sure it deletes the v1 functions uuid's and hash'es. 
Maybe write a little migration tutorial?

**Comment by NickolausDS** [comment]
Hmm, that's a good point. 

FuncX doesn't provide a way to check which service a function UUID is from, so I think we'd have to do the tracking all in Gladier. Here's one solution:

Gladier will track its current version in the `.gladier-secrets.cfg`. If it detects its current version is different from its config version, it will run through a migration.

**Comment by ravescovi** [comment]
If there was a gladier tool that could inspect the installation and return
some info.
Would that solve the problem?

**Comment by NickolausDS** [comment]
No, this all has to be done by Gladier. Gladier tools don't handle any registration.

**Comment by NickolausDS** [comment]
In the interest of time, I'm going to go ahead and merge this and make a prerelease for v0.4

**Pull request merged**
