### PR TITLE
[WIP] Feature for using multiple Gladier tools in a Gladier Client

### PR DESCRIPTION
**Pull request by NickolausDS**
~~This technically works, but isn't all that useful in its current state. It will properly rename the states and ensure the duplicated states point to the right spot in the flow definition chain. However, flow modifiers aren't sophisticated enough to reset variables on the duplicated states. So for most cases, this isn't too useful yet.~~

**EDIT**: Updated to show latest functionality with `Transfer:FromSource`. 

For example:
```
@generate_flow_definition
class TarAndTransfer(GladierBaseClient):
    gladier_tools = [
        'gladier_tools.globus.Transfer:FromStorage',
        'gladier_tools.posix.Tar',
        'gladier_tools.globus.Transfer:ToStorage',
    ]
```

Creates the flow definition below:

```
{'Comment': 'Flow with states: TransferFromStorage, Tar, TransferToStorage',
 'StartAt': 'TransferFromStorage',
 'States': {'Tar': {'ActionScope': 'https://auth.globus.org/scopes/b3db7e59-a6f1-4947-95c2-59d6b7a70f8c/action_all',
                    'ActionUrl': 'https://automate.funcx.org',
                    'Comment': None,
                    'ExceptionOnActionFailure': True,
                    'Next': 'TransferToStorage',
                    'Parameters': {'tasks': [{'endpoint.$': '$.input.funcx_endpoint_compute',
                                              'function.$': '$.input.tar_funcx_id',
                                              'payload.$': '$.input'}]},
                    'ResultPath': '$.Tar',
                    'Type': 'Action',
                    'WaitTime': 300},
            'TransferFromStorage': {'ActionUrl': 'https://actions.automate.globus.org/transfer/transfer',
                                    'Comment': 'Transfer a file or directory '
                                               'in Globus',
                                    'Next': 'Tar',
                                    'Parameters': {'destination_endpoint_id.$': '$.input.from_storage_transfer_destination_endpoint_id',
                                                   'source_endpoint_id.$': '$.input.from_storage_transfer_source_endpoint_id',
                                                   'transfer_items': [{'destination_path.$': '$.input.from_storage_transfer_destination_path',
                                                                       'recursive.$': '$.input.from_storage_transfer_recursive',
                                                                       'source_path.$': '$.input.from_storage_transfer_source_path'}]},
                                    'ResultPath': '$.Transfer',
                                    'Type': 'Action',
                                    'WaitTime': 600},
            'TransferToStorage': {'ActionUrl': 'https://actions.automate.globus.org/transfer/transfer',
                                  'Comment': 'Transfer a file or directory in '
                                             'Globus',
                                  'End': True,
                                  'Parameters': {'destination_endpoint_id.$': '$.input.to_storage_transfer_destination_endpoint_id',
                                                 'source_endpoint_id.$': '$.input.to_storage_transfer_source_endpoint_id',
                                                 'transfer_items': [{'destination_path.$': '$.input.to_storage_transfer_destination_path',
                                                                     'recursive.$': '$.input.to_storage_transfer_recursive',
                                                                     'source_path.$': '$.input.to_storage_transfer_source_path'}]},
                                  'ResultPath': '$.Transfer',
                                  'Type': 'Action',
                                  'WaitTime': 600}}}
```

### CODE REVIEW

**Comment by NickolausDS** [comment]
Whoops, this should be a Draft. It shouldn't be merged yet...

**Comment by ravescovi** [comment]
Does it start renaming only after n>1.
We should agree on nomenclature. I would also tie this PR with the v2 upgrade and the modifiers on tool name only.

**Comment by NickolausDS** [comment]
It only renames in the case of a name 'collision'. That is, if you add two tools with the same name and Gladier detects more than one, it will automatically rename the second one in the list. 

I think the major downside to this approach is the naming is automatic, and may not be obvious to the user which tool corresponds to which state. That's a problem when a user wants to modify attributes on a given state. The approach here would take the 'ask forgiveness not permission' route and do the renaming automatically without the users consent, then give a detailed exception if anything went wrong.  

Adding this link to modifiers too https://github.com/globus-gladier/gladier/issues/93

**Comment by ravescovi** [comment]
Instead of the renaming trying to find the colisions and then creating a whole new tool. Would not be easy to pass a dict with `tool:tool_name` ?

**Comment by NickolausDS** [comment]
I don't think I follow? I do need to up date the example in the PR description, which is old. But the newest changes here allow for re-using tools without creating a new one. Collisions are still not allowed, so the following will fail with an error: 

```
    gladier_tools = [
        'gladier_tools.globus.Transfer',
        'gladier_tools.posix.Tar',
        'gladier_tools.globus.Transfer',
    ]
```

But the following is valid if the names are 'aliased'.

```
    gladier_tools = [
        'gladier_tools.globus.Transfer:FromStorage',
        'gladier_tools.posix.Tar',
        'gladier_tools.globus.Transfer:ToStorage',
    ]
```

**Comment by NickolausDS** [comment]
I went ahead and added unit tests to this one. I also updated the flow definition in the main description to show how the actual flow input vars are transformed. Below is the input I used (I didn't use Tar, since I don't have an ep handy):

```
    flow_input = {
        'input': {

            'from_storage_transfer_source_path': '/share/godata',
            'from_storage_transfer_destination_path': '~',
            'from_storage_transfer_source_endpoint_id': 'ddb59aef-6d04-11e5-ba46-22000b92c6ec',
            'from_storage_transfer_destination_endpoint_id': 'ddb59aef-6d04-11e5-ba46-22000b92c6ec',
            'from_storage_transfer_recursive': True,

            'to_storage_transfer_source_path': '/share/godata',
            'to_storage_transfer_destination_path': '~',
            'to_storage_transfer_source_endpoint_id': 'ddb59aef-6d04-11e5-ba46-22000b92c6ec',
            'to_storage_transfer_destination_endpoint_id': 'ddb59aef-6d04-11e5-ba46-22000b92c6ec',
            'to_storage_transfer_recursive': True,
        }
```

**Comment by ravescovi** [comment]
If possible, I would like to merge that to add into the SSX repo.

**Comment by NickolausDS** [comment]
Sure! This should be good to go, I don't have anything else to add unless you see something out of place.

**Comment by NickolausDS** [comment]
@jimPruyne Although this doesn't break compatibility, it does complicate tools a bit more. Giving you a ping for visibility.

**Pull request merged**
