### PR TITLE
refactor!: Remove Globus-Automate-Client dependency

### PR DESCRIPTION
**Pull request by NickolausDS**
Remove the globus-automate-client dependency in favor of calling into the base globus-sdk instead

### CODE REVIEW

**Comment by jimPruyne** [comment]
@NickolausDS You didn't ask me to review, but I did browse through this relatively quickly and it seems pretty good to me. Overall, the idea of deprecating globus-automate-client usage seems like a good one if the automate/sdk dev team(s) are doing so as well. If nothing else, its the first I've looked at the globus sdk proper integration for flows so I learned something at least.

**Comment by NickolausDS** [comment]
Thanks Jim! I might do another pass on this just to make sure there aren't any hidden failures with the Globus SDK. I didn't fully test this outside of just making sure the unit tests pass.

**Comment by NickolausDS** [comment]
Dependent on #268

**Comment by NickolausDS** [comment]
@jimPruyne Should be good to go

**Comment by NickolausDS** [comment]
I had to rebase to remove unrelated commits. The last relevant commit was this one that fixed some improper calls to the Globus SDK:
https://github.com/globus-gladier/gladier/pull/259/commits/1266bc02cbfba7d1cdbdd36e891dfd19be53fb40

**Pull request merged**
