### PR TITLE
Added Config Migration system + docs for upgrading

### PR DESCRIPTION
**Pull request by NickolausDS**
So far, it includes the following:

- [x] Doc for upgrading
- [x] A simple migrator to delete old FuncX functions
- [x] Tests

### CODE REVIEW

**Review by ravescovi — APPROVED** [review]
I did not test it but the changes look good. We could test applying it on the SSX template later today.

**Comment by NickolausDS** [comment]
This should be good to go now. I'll test it with XPCS today and see if I find any problems.

**Comment by ravescovi** [comment]
SSX may be better.

**Comment by NickolausDS** [comment]
Ok, added one final migration step to account for the result format on FuncX changing. Tested on XPCS, and everything is looking good. If no one sees any problems, this should be good to go!

**Comment by NickolausDS** [comment]
Changes for #102

**Pull request merged**
